management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.springframework.data: debug

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github.client-id:fake-value-to-start-the-app}
            client-secret: ${github.client-secret:fake-value-to-start-the-app}
        provider:
          github:
            user-name-attribute: name
